from .grade import GradeSerializer
from .gradeGroup import GradeGroupSerializer
from .subject import SubjectSerializer
from .groupWithGroupsOfGrades import GroupWithGroupsOfGradesSerializer
from .extensionCourse import ExtensionCourseSerializer
from .gradeDefinition import GradeDefinitionSerializer
