# Generated by Django 4.2.1 on 2023-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('academicPrograms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('places', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=12)),
                ('grade_group_score', models.FloatField()),
                ('grade_group_state', models.CharField(choices=[('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], max_length=10)),
                ('percentage_in_subject', models.FloatField()),
                ('is_final_general_grade', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('schedule_intensity', models.IntegerField()),
                ('place_in_semester', models.IntegerField()),
                ('pre_requisite', models.CharField(max_length=6, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPrograms.academicprogram')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectWithGroupsOfGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.gradegroup')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='gradegroup',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('grade_score', models.FloatField()),
                ('grade_state', models.CharField(choices=[('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], max_length=10)),
                ('percentage_in_group', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.gradegroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
