# Generated by Django 4.2.1 on 2023-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradegroup',
            name='grade_group_score',
        ),
        migrations.RemoveField(
            model_name='gradegroup',
            name='grade_group_state',
        ),
        migrations.RemoveField(
            model_name='gradegroup',
            name='is_final_general_grade',
        ),
    ]
