# Generated by Django 4.2.1 on 2023-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_remove_gradegroup_grade_group_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
