# Generated by Django 4.2.1 on 2023-12-02 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_gradegroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade_group_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='percentage_in_group',
        ),
        migrations.AlterField(
            model_name='grade',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='GradeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage_in_group', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.gradegroup')),
            ],
        ),
    ]
