# Generated by Django 4.2.1 on 2023-12-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_grade_grade_definition_id_alter_grade_grade_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_score',
            field=models.FloatField(default=0.0),
        ),
    ]
