# Generated by Django 4.2.1 on 2023-12-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_alter_grade_grade_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
    ]
