# Generated by Django 4.2.1 on 2023-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_identification_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='personal_phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
