# Generated by Django 4.2.1 on 2023-11-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicPrograms', '0002_academicprogramwithsubjects_subject_id'),
        ('users', '0005_rename_phone_number_userprofile_personal_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academicPrograms.academicprogram'),
        ),
    ]
