# Generated by Django 4.2.1 on 2023-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('period', models.CharField(max_length=6)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangesInSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('date', models.DateField()),
                ('verification_file', models.FileField(upload_to='ChangesInSubject')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPrograms.academicprogram')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgramWithSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('academic_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPrograms.academicprogram')),
            ],
        ),
    ]
