# Generated by Django 4.2.1 on 2023-11-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_gradegroup_subject_id_and_more'),
        ('academicPrograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogramwithsubjects',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
